# Generated by Django 3.1.4 on 2021-01-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_starred_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starred',
            name='save',
        ),
    ]
