# Generated by Django 3.1.4 on 2021-01-03 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_remove_starred_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='starred',
            name='saved',
            field=models.ManyToManyField(related_name='savepost', to=settings.AUTH_USER_MODEL),
        ),
    ]
